/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

import Modelo.Aviso;
import Modelo.Trabajador;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sirlocus
 */
public class AdministrativoHome extends javax.swing.JFrame {

    private CentroFormulario cf;
    private CentroDetalle cd;
    private CentroListado cl;
    private TrabajadorFormulario tf;
    private TrabajadorDetalle td;
    private TrabajadorListado tl;
    private DefaultTableModel dm;
    private ArrayList<Aviso> avisos;
    private Trabajador t = Modelo.Usuario.getT();
    private TodosLosPartes tp;
    private int id;
    
    /** Creates new form AdministrativoHome */
    
    public AdministrativoHome() {
        initComponents();
        recargarTabla();
    }

    private void recargarTabla(){
        dm= (DefaultTableModel)jTable1.getModel();
        avisos = Aviso.listarAvisos(t.getId_trabajador());
        for(Aviso a:avisos){
            dm.insertRow(dm.getRowCount(), new Object[]{a.getIdAviso(),a.getNombreE(),a.getTexto()});
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        jltitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbBorrar = new javax.swing.JButton();
        jlAviso = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmNuevoCen = new javax.swing.JMenuItem();
        jmTrabaCentro = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmNuevoTrab = new javax.swing.JMenuItem();
        jmListarTrab = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmNuevoUsu = new javax.swing.JMenuItem();
        jmDetalleUsu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmTodos = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("jCheckBoxMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jltitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jltitulo.setText("Bienvenido ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Aviso", "Trabajador", "Observaciones"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jbBorrar.setText("Borrar aviso");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jlAviso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlAviso.setForeground(new java.awt.Color(0, 204, 0));

        jMenu1.setText("Centros");

        jmNuevoCen.setText("Nuevo centro");
        jmNuevoCen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNuevoCenActionPerformed(evt);
            }
        });
        jMenu1.add(jmNuevoCen);

        jmTrabaCentro.setText("Listado centros");
        jmTrabaCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTrabaCentroActionPerformed(evt);
            }
        });
        jMenu1.add(jmTrabaCentro);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Trabajadores");

        jmNuevoTrab.setText("Nuevo trabajador");
        jmNuevoTrab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNuevoTrabActionPerformed(evt);
            }
        });
        jMenu2.add(jmNuevoTrab);

        jmListarTrab.setText("Listar trabajadores");
        jmListarTrab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListarTrabActionPerformed(evt);
            }
        });
        jMenu2.add(jmListarTrab);
        jMenu2.add(jSeparator2);

        jmNuevoUsu.setText("Nuevo usuario");
        jMenu2.add(jmNuevoUsu);

        jmDetalleUsu.setText("Detalle usuario");
        jMenu2.add(jmDetalleUsu);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Partes");

        jmTodos.setText("Ver todos los partes");
        jmTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTodosActionPerformed(evt);
            }
        });
        jMenu3.add(jmTodos);
        jMenu3.add(jSeparator1);

        jCheckBoxMenuItem4.setText("Buscar parte");
        jCheckBoxMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jCheckBoxMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jbBorrar)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBorrar)
                    .addComponent(jlAviso))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmNuevoCenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNuevoCenActionPerformed
        cf = new CentroFormulario();
        cf.setVisible(true);
    }//GEN-LAST:event_jmNuevoCenActionPerformed

    private void jmTrabaCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTrabaCentroActionPerformed
        cl = new CentroListado();
        cl.setVisible(true);
    }//GEN-LAST:event_jmTrabaCentroActionPerformed

    private void jmNuevoTrabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNuevoTrabActionPerformed
        tf = new TrabajadorFormulario();
        tf.setVisible(true);
    }//GEN-LAST:event_jmNuevoTrabActionPerformed

    private void jmListarTrabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListarTrabActionPerformed
        tl = new TrabajadorListado();
        tl.setVisible(true);
    }//GEN-LAST:event_jmListarTrabActionPerformed

    private void jmTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTodosActionPerformed
        tp= new TodosLosPartes();
        tp.setAh(this);
        tp.setVisible(true);
    }//GEN-LAST:event_jmTodosActionPerformed

    private void jCheckBoxMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();
        id = Integer.parseInt(dm.getValueAt(fila,0).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        Aviso a = new Aviso();
        a.setIdAviso(id);
        boolean correcto = a.borrarAviso();
        if(correcto){
            jlAviso.setText("Borrado correctamente");
            //TODO no se recarga la tabla
            recargarTabla();
        }
    }//GEN-LAST:event_jbBorrarActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrativoHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrativoHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrativoHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrativoHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrativoHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JLabel jlAviso;
    private javax.swing.JLabel jltitulo;
    private javax.swing.JMenuItem jmDetalleUsu;
    private javax.swing.JMenuItem jmListarTrab;
    private javax.swing.JMenuItem jmNuevoCen;
    private javax.swing.JMenuItem jmNuevoTrab;
    private javax.swing.JMenuItem jmNuevoUsu;
    private javax.swing.JCheckBoxMenuItem jmTodos;
    private javax.swing.JMenuItem jmTrabaCentro;
    // End of variables declaration//GEN-END:variables

}
