/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 7fbd06
 */
public class AdministrativoPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form AdministrativoPrincipal
     */
    public AdministrativoPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearCentroBoton = new javax.swing.JButton();
        crearTrabajadorBoton = new javax.swing.JButton();
        crearusuarioBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        crearCentroBoton.setText("Crear un Centro");
        crearCentroBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCentroBotonActionPerformed(evt);
            }
        });

        crearTrabajadorBoton.setText("Crear un trabajador");
        crearTrabajadorBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearTrabajadorBotonActionPerformed(evt);
            }
        });

        crearusuarioBoton.setText("Crear un usuario");
        crearusuarioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearusuarioBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(crearCentroBoton)
                .addGap(87, 87, 87)
                .addComponent(crearTrabajadorBoton)
                .addGap(94, 94, 94)
                .addComponent(crearusuarioBoton)
                .addContainerGap(403, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearCentroBoton)
                    .addComponent(crearTrabajadorBoton)
                    .addComponent(crearusuarioBoton))
                .addContainerGap(703, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearCentroBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCentroBotonActionPerformed
        CentroFormulario cf=new CentroFormulario();
        cf.setVisible(true);
    }//GEN-LAST:event_crearCentroBotonActionPerformed

    private void crearusuarioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearusuarioBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearusuarioBotonActionPerformed

    private void crearTrabajadorBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearTrabajadorBotonActionPerformed
        TrabajadorFormulario tf = null;
        try {
            tf = new TrabajadorFormulario();
        } catch (SQLException ex) {
            Logger.getLogger(AdministrativoPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        tf.setVisible(true);
    }//GEN-LAST:event_crearTrabajadorBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrativoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrativoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrativoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrativoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrativoPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearCentroBoton;
    private javax.swing.JButton crearTrabajadorBoton;
    private javax.swing.JButton crearusuarioBoton;
    // End of variables declaration//GEN-END:variables
}
