/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Modelo.Centro;
import Modelo.ControladorBaseDatos;
import java.net.ContentHandlerFactory;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author 7fbd06
 */
public class CentroDetalle extends javax.swing.JFrame {
    
    private int contador=0;

    /**
     * Creates new form CentroDetalle
     */
    
   

    public CentroDetalle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void añadeCentro(){
        
    }
    
   
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombreTexto = new javax.swing.JTextField();
        direccionTexto = new javax.swing.JTextField();
        cpTexto = new javax.swing.JTextField();
        loctexto = new javax.swing.JTextField();
        provTexto = new javax.swing.JTextField();
        telfTexto = new javax.swing.JTextField();
        anteriorBoton = new javax.swing.JButton();
        siguienteBoton = new javax.swing.JButton();
        borrarBoton = new javax.swing.JButton();
        editarBoton = new javax.swing.JButton();
        guardarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NOMBRE:");

        jLabel2.setText("DIRECCIÓN:");

        jLabel3.setText("CÓDIGO POSTAL:");

        jLabel4.setText("LOCALIDAD:");

        jLabel5.setText("PROVINCIA:");

        jLabel6.setText("TELÉFONO:");

        nombreTexto.setEditable(false);

        direccionTexto.setEditable(false);

        cpTexto.setEditable(false);
        cpTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpTextoActionPerformed(evt);
            }
        });

        loctexto.setEditable(false);

        provTexto.setEditable(false);

        telfTexto.setEditable(false);

        anteriorBoton.setText("Anterior");
        anteriorBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorBotonActionPerformed(evt);
            }
        });

        siguienteBoton.setText("Siguiente");
        siguienteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteBotonActionPerformed(evt);
            }
        });

        borrarBoton.setText("Borrar");
        borrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarBotonActionPerformed(evt);
            }
        });

        editarBoton.setText("Editar");
        editarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBotonActionPerformed(evt);
            }
        });

        guardarBoton.setText("Guardar");
        guardarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(provTexto)
                    .addComponent(loctexto)
                    .addComponent(cpTexto)
                    .addComponent(direccionTexto)
                    .addComponent(nombreTexto)
                    .addComponent(telfTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(anteriorBoton)
                .addGap(200, 200, 200)
                .addComponent(borrarBoton)
                .addGap(70, 70, 70)
                .addComponent(editarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(siguienteBoton)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(direccionTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cpTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(loctexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(provTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(telfTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anteriorBoton)
                    .addComponent(siguienteBoton)
                    .addComponent(borrarBoton)
                    .addComponent(editarBoton)
                    .addComponent(guardarBoton))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpTextoActionPerformed

    private void anteriorBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorBotonActionPerformed
        try {
            contador--;
            Centro c=new Centro();
            nombreTexto.setText(c.verCentro().get(contador).getNombre());
            direccionTexto.setText(c.verCentro().get(contador).getDireccion());
            cpTexto.setText(c.verCentro().get(contador).getCp());
            loctexto.setText(c.verCentro().get(contador).getLoc());
            provTexto.setText(c.verCentro().get(contador).getProvincia());
            telfTexto.setText(c.verCentro().get(contador).getTelf());
            
        } catch (SQLException ex) {
            Logger.getLogger(CentroListado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_anteriorBotonActionPerformed

    private void editarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBotonActionPerformed
        nombreTexto.setEditable(rootPaneCheckingEnabled);
        direccionTexto.setEditable(rootPaneCheckingEnabled);
        cpTexto.setEditable(rootPaneCheckingEnabled);
        loctexto.setEditable(rootPaneCheckingEnabled);
        provTexto.setEditable(rootPaneCheckingEnabled);
        telfTexto.setEditable(rootPaneCheckingEnabled);
        
    }//GEN-LAST:event_editarBotonActionPerformed

    private void siguienteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteBotonActionPerformed
         try {
            Centro c=new Centro();
            
            nombreTexto.setText(c.verCentro().get(contador).getNombre());
            direccionTexto.setText(c.verCentro().get(contador).getDireccion());
            cpTexto.setText(c.verCentro().get(contador).getCp());
            loctexto.setText(c.verCentro().get(contador).getLoc());
            provTexto.setText(c.verCentro().get(contador).getProvincia());
            telfTexto.setText(c.verCentro().get(contador).getTelf());
            contador++;
        } catch (SQLException ex) {
            Logger.getLogger(CentroListado.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_siguienteBotonActionPerformed

    private void guardarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBotonActionPerformed
        
        Centro c =new Centro(contador,nombreTexto.getText(),direccionTexto.getText(),cpTexto.getText(),
                            loctexto.getText(),provTexto.getText(),telfTexto.getText());
                   c.modificarCentro();
    }//GEN-LAST:event_guardarBotonActionPerformed

    private void borrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBotonActionPerformed
       int id_centro=0;
        try {
            ControladorBaseDatos.conectar();
        String query="{call ID_CENTRO_NOMBRE (?,?)}";
        CallableStatement cst=ControladorBaseDatos.getConexion().prepareCall(query);
        cst.setString(1, nombreTexto.getText());
        cst.registerOutParameter(2, OracleTypes.CURSOR);
        cst.execute();
        ResultSet rs= (ResultSet)cst.getObject(1);
        while(rs.next()){
           
             id_centro=rs.getInt("ID_CENTRO");
            
        }
            ControladorBaseDatos.desconectar();
        } catch (Exception e) {
           
        }
    }//GEN-LAST:event_borrarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CentroDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CentroDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CentroDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CentroDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CentroDetalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anteriorBoton;
    private javax.swing.JButton borrarBoton;
    private javax.swing.JTextField cpTexto;
    private javax.swing.JTextField direccionTexto;
    private javax.swing.JButton editarBoton;
    private javax.swing.JButton guardarBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField loctexto;
    private javax.swing.JTextField nombreTexto;
    private javax.swing.JTextField provTexto;
    private javax.swing.JButton siguienteBoton;
    private javax.swing.JTextField telfTexto;
    // End of variables declaration//GEN-END:variables
}
