INSERT INTO CENTRO(NOMBRE,DIRECCION,CP,LOC,PROVINCIA,TELF) VALUES('NOMRE','Direccion','CP','LOC','PROV','TEL');
INSERT INTO TRABAJADOR(DNI,NOMBRE,AP1,AP2,DIRECCION,TELF_EMPRESA,TELF_PERSONAL,CATEGORIA,SALARIO,FECHANAC,ID_CENTRO) 
VALUES('12312312A','Nombre','Apellido','Apellido','Direccion','654644654','945945945','Administrativo',1200,sysdate,1);
INSERT INTO CENTRO(NOMBRE,DIRECCION,CP,LOC,PROVINCIA,TELF) VALUES('Nombre','Direccion','12345','Localidad','Provincia','987987987');
INSERT INTO USUARIO VALUES('TeHenua',ora_hash('aaaaa'));
UPDATE TRABAJADOR SET ID_USUARIO='TeHenua' WHERE ID_TRABAJADOR=2;
COMMIT;
update usuario set "CONTRASEÑA"=ora_hash('aaaaa') where id_usuario='TeHenua';
select * from usuario;
select * from trabajador;
select * from centro;
DROP TABLE TRABAJADOR CASCADE CONSTRAINTS;

DESC TRABAJADOR;

INSERT INTO VEHICULO(MATRICULA,MARCA,MODELO) VALUES('MATRICULA','MODELO','MARCA');
INSERT INTO PARTE VALUES('03/05/17',21,1,5,NULL,NULL,NULL,NULL,NULL,0,NULL,0,1);
INSERT INTO REPARTO VALUES('03/05/17',21,13458,'03/05/17 21:20:00','03/05/17 21:26:00');
INSERT INTO REPARTO VALUES('03/05/17',21,138,'03/05/17 21:00:00','03/05/17 21:56:00');

COMMIT;
DELETE FROM REPARTO;
DESCRIBE PARTE;
DROP TABLE REPARTO CASCADE CONSTRAINTS;

SELECT EXTRACT(MINUTE FROM(HORA_FIN - HORA_INICIO)) FROM REPARTO WHERE ALBARAN=13456;
SELECT SUM(EXTRACT(HOUR FROM(HORA_FIN - HORA_INICIO)) + interval (EXTRACT(MINUTE FROM(HORA_FIN-HORA_INICIO)))) minute FROM REPARTO WHERE FECHA='25/04/17';

select minutos_a_horas(30) from dual;

CREATE OR REPLACE FUNCTION MINUTOS_A_HORAS(HORA IN number )
  RETURN  PARTE.EXCESO_HORAS%TYPE
AS
  NUMERO  PARTE.EXCESO_HORAS%TYPE;
  MINUTOS PARTE.EXCESO_HORAS%TYPE;
BEGIN
  MINUTOS:=mod(HORA,60);
  NUMERO := (HORA-MINUTOS)/60;
  RETURN NUMERO;
END MINUTOS_A_HORAS;

select sum(extract(day from 24*60*(hora_fin - hora_inicio))) from reparto;

select interval '40' minute from dual;

SELECT * FROM PARTE WHERE ABIERTO = 1 AND ID_TRABAJADOR=21;

SELECT * FROM REPARTO WHERE ID_TRABAJADOR=1 AND FECHA ='26/04/17';

SELECT FECHA FROM PARTE WHERE FECHA = '03/05/17';
    SELECT MATRICULA, MODELO, MARCA FROM VEHICULO WHERE ID_VEHICULO=(SELECT ID_VEHICULO FROM PARTE WHERE FECHA ='03/05/17' AND ID_TRABAJADOR=21) ;
SELECT * FROM TRABAJADOR WHERE ID_USUARIO='aaaaa';
  SELECT ID_TRABAJADOR  FROM TRABAJADOR WHERE ID_USUARIO='aaaaa';
  SELECT FECHA FROM PARTE WHERE ABIERTO = 1 AND ID_TRABAJADOR=21;
SELECT ID_VEHICULO FROM PARTE WHERE FECHA ='03/05/17' AND ID_TRABAJADOR=21;