create or replace PACKAGE VISTAS_CENTROS IS
  PROCEDURE TODOS_CENTROS (CURSOR1 OUT SYS_REFCURSOR);
  PROCEDURE UN_CENTRO (ID_CENTRO_V IN APLICACION.CENTRO.ID_CENTRO%TYPE,DATOS OUT SYS_REFCURSOR);
END;
create or replace PACKAGE BODY VISTAS_CENTROS IS
  PROCEDURE TODOS_CENTROS (CURSOR1 OUT SYS_REFCURSOR)
AS
NO_DATA_FOUND EXCEPTION;
OTHERS EXCEPTION;
BEGIN
  OPEN CURSOR1 FOR
  SELECT NOMBRE, LOC FROM APLICACION.CENTRO;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
  RAISE NO_DATA_FOUND;
  WHEN OTHERS THEN
  RAISE OTHERS;
END TODOS_CENTROS;
  PROCEDURE UN_CENTRO (ID_CENTRO_V IN APLICACION.CENTRO.ID_CENTRO%TYPE,DATOS OUT SYS_REFCURSOR)
AS
NO_DATA_FOUND EXCEPTION;
TOO_MANY_ROWS EXCEPTION;
OTHERS EXCEPTION;
BEGIN
  OPEN DATOS FOR 
  SELECT * FROM APLICACION.CENTRO 
  WHERE ID_CENTRO=ID_CENTRO_V;
EXCEPTION 
  WHEN NO_DATA_FOUND THEN
  RAISE NO_DATA_FOUND;
  WHEN TOO_MANY_ROWS THEN
  RAISE TOO_MANY_ROWS;
  WHEN OTHERS THEN
  RAISE OTHERS;
END UN_CENTRO;
END VISTAS_CENTROS;


create or replace PROCEDURE TODOS_TRABAJADORES
(CURSOR1 OUT SYS_REFCURSOR)
AS
NO_DATA_FOUND EXCEPTION;
OTHERS EXCEPTION;
BEGIN
  OPEN CURSOR1 FOR
  SELECT NOMBRE, AP1 , AP2  FROM APLICACION.TRABAJADOR;
EXCEPTION 
  WHEN NO_DATA_FOUND THEN
  RAISE NO_DATA_FOUND;
  WHEN OTHERS THEN
  RAISE OTHERS;
END TODOS_TRABAJADORES;

create or replace PROCEDURE UN_TRABAJADOR
(ID_TRABAJADOR_V IN TRABAJADOR.ID_TRABAJADOR%TYPE,
DATOS OUT SYS_REFCURSOR)
AS
NO_DATA_FOUND EXCEPTION;
TOO_MANY_ROWS EXCEPTION;
OTHERS EXCEPTION;
BEGIN
OPEN DATOS FOR
  SELECT *  FROM APLICACION.TRABAJADOR 
  WHERE ID_TRABAJADOR=ID_TRABAJADOR_V;
EXCEPTION 
  WHEN NO_DATA_FOUND THEN
  RAISE NO_DATA_FOUND;
  WHEN TOO_MANY_ROWS THEN
  RAISE TOO_MANY_ROWS;
  WHEN OTHERS THEN
  RAISE OTHERS;
END UN_TRABAJADOR;

create or replace PROCEDURE LOGIN
(ID_ENTRANTE USUARIO.ID_USUARIO%TYPE,
CONTRASEÑA_ENTRANTE USUARIO.CONTRASEÑA%TYPE,
CATEGORIA_V OUT VARCHAR2)
AS
ORIGINAL USUARIO.CONTRASEÑA%TYPE;
ENCRIPTADA USUARIO.CONTRASEÑA%TYPE;
BEGIN
  SELECT "CONTRASEÑA" INTO ENCRIPTADA FROM USUARIO WHERE ID_USUARIO=ID_ENTRANTE  ;
  SELECT ORA_HASH(CONTRASEÑA_ENTRANTE) INTO ORIGINAL  FROM DUAL;
  IF ENCRIPTADA = ORIGINAL THEN
    SELECT CATEGORIA INTO CATEGORIA_V FROM TRABAJADOR WHERE ID_USUARIO=ID_ENTRANTE;
  END IF;
END LOGIN;