--PROCEDIMIENTO LISTAR TODOS LOS TRABAJADORES 
 
CREATE OR REPLACE PROCEDURE CONSULTA_TRABAJADORES(C_TRA OUT SYS_REFCURSOR) 
AS 
  SIN_DATOS EXCEPTION; 
  OTRO_ERROR EXCEPTION; 
BEGIN 
  OPEN C_TRA FOR 
  SELECT ID_TRABAJADOR,NOMBRE,AP1,AP2 FROM TRABAJADOR; 
EXCEPTION 
  WHEN NO_DATA_FOUND THEN 
    RAISE SIN_DATOS; 
  WHEN OTHERS THEN 
    RAISE OTRO_ERROR;     
END CONSULTA_TRABAJADORES; 
 
--PROCEDIMIENTO LISTAR UN TRABAJADOR 
 
CREATE OR REPLACE PROCEDURE CONSULTA_TRABAJADOR(ID_TRA IN TRABAJADOR.ID_TRABAJADOR%TYPE, 
  C_TRA OUT SYS_REFCURSOR ) 
AS 
  SIN_DATOS EXCEPTION; 
  OTRO_ERROR EXCEPTION; 
  MAS_LINEAS EXCEPTION; 
BEGIN 
  OPEN C_TRA FOR
    SELECT * FROM TRABAJADOR WHERE ID_TRABAJADOR=ID_TRA; 
EXCEPTION 
  WHEN NO_DATA_FOUND THEN 
    RAISE SIN_DATOS;    
  WHEN TOO_MANY_ROWS THEN 
    RAISE MAS_LINEAS;
  WHEN OTHERS THEN 
    RAISE OTRO_ERROR;  
END CONSULTA_TRABAJADOR; 
 
--PAQUETE LISTAR CENTROS 
 
CREATE OR REPLACE PACKAGE PAQ_CENTROS 
AS 
  SIN_DATOS EXCEPTION; 
  OTRO_ERROR EXCEPTION; 
  MAS_LINEAS EXCEPTION; 
PROCEDURE CONSULTA_CENTRO(ID_CEN IN CENTRO.ID_CENTRO%TYPE, 
  C_CEN OUT SYS_REFCURSOR); 
PROCEDURE CONSULTA_CENTROS(C_CEN OUT CURSOR); 
END PAQ_CENTROS; 
 
CREATE OR REPLACE PACKAGE BODY PAQ_CENTROS  
AS 
PROCEDURE CONSULTA_CENTRO(ID_CEN IN CENTRO.ID_CENTRO%TYPE, 
  C_CEN OUT SYS_REFCURSOR)
  AS 
  BEGIN 
    OPEN C_CEN FOR
      SELECT * FROM CENTRO WHERE ID_CENTRO=ID_CEN; 
  EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
      RAISE SIN_DATOS;   
    WHEN TOO_MANY_ROWS THEN 
      RAISE MAS_LINEAS; 
    WHEN OTHERS THEN 
      RAISE OTRO_ERROR;  
  END CONSULTA_CENTRO; 
  PROCEDURE CONSULTA_CENTROS(C_CEN OUT SYS_REFCURSOR) 
  AS 
  BEGIN 
    OPEN C_CEN FOR 
    SELECT ID_CENTRO,NOMBRE,LOC FROM CENTRO; 
  EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
      RAISE SIN_DATOS; 
    WHEN OTHERS THEN 
      RAISE OTRO_ERROR;    
  END CONSULTA_CENTROS; 
END PAQ_CENTROS; 

--PROCEDIMIENTO LOGIN

CREATE OR REPLACE PROCEDURE USUARIO_LOGIN(USU IN USUARIO.ID_USUARIO%TYPE,
CON IN USUARIO.CONTRASEÑA%TYPE)
AS
  USUARIO_CONTRA_ERROR EXCEPTION; 
  OTRO_ERROR EXCEPTION; 
  USU_ENCONTRADO USUARIO.ID_USUARIO%TYPE;
  CON_ENCONTRADO USUARIO."CONTRASEÑA"%TYPE;
BEGIN
  SELECT "CONTRASEÑA" INTO CON_ENCONTRADO FROM USUARIO WHERE ID_USUARIO=USU AND "CONTRASEÑA"=ORA_HASH(CON);
EXCEPTION
  WHEN NO_DATA_FOUND THEN 
    RAISE USUARIO_CONTRA_ERROR;
  WHEN OTHERS THEN
    RAISE OTRO_ERROR;
END USUARIO_NUEVO;

--PROCEDIMIENTO GUARDAR USUARIO

CREATE OR REPLACE PROCEDURE USUARIO_NUEVO(USU IN USUARIO.ID_USUARIO%TYPE,
CON IN USUARIO.CONTRASEÑA%TYPE)
AS
  USUARIO_REPETIDO EXCEPTION; 
  OTRO_ERROR EXCEPTION; 
  USU_REPETIDO USUARIO.ID_USUARIO%TYPE;
BEGIN
  SELECT ID_USUARIO INTO USU_REPETIDO FROM USUARIO WHERE ID_USUARIO=USU;
  IF(USU_REPETIDO IS NOT NULL) THEN
    RAISE USUARIO_REPETIDO;
  END IF;
  INSERT INTO USUARIO VALUES(USU,ORA_HASH(CON));
EXCEPTION
  WHEN USUARIO_REPETIDO THEN 
    RAISE USUARIO_REPETIDO;
  WHEN OTHERS THEN
    RAISE OTRO_ERROR;
END USUARIO_NUEVO;